name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Archive dist folder
        run: tar -czf dist.tar.gz dist

      - name: Upload dist.tar.gz to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist.tar.gz"
          target: "~/"

      - name: Extract dist.tar.gz and restart nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/vite-app
            rm -rf ~/vite-app/dist
            tar -xzf ~/dist.tar.gz -C ~/vite-app
            rm ~/dist.tar.gz
            sudo systemctl reload nginx
